#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      brew install wget
      brew cask install java
      return
      ;;
    Ubuntu)
      ${NOSUDO} sudo apt-get install -y openjdk-8-jre
      return
      ;;
  esac
      
  local platform='linux-x64.tar.gz'

  case "${DISTRIB_ID}" in
    Alpine)
      curl -O https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.26-r0/glibc-2.26-r0.apk -k -L
      ${NOSUDO} sudo apk add --allow-untrusted ./glibc-2.26-r0.apk
      rm -f ./glibc-2.26-r0.apk
      ;;
  esac

  ${NOSUDO} sudo chown ubuntu:ubuntu "${DATA}"
  mkdir -p "${DATA}/cache/nodist"
  if [[ ! -f "${DATA}/cache/nodist/${JAVA_VERSION}$platform" ]]; then
    wget -c -O "${DATA}/cache/nodist/${JAVA_VERSION}$platform" --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "${JAVA_URL}${platform}"
  fi

  mkdir -p "$shome/vendor"
  pushd "$shome/vendor"
  tar xfz "${DATA}/cache/nodist/${JAVA_VERSION}$platform"
  popd
}

bootstrap
