#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      brew cask install java
      ;;
    Linux)
      mkdir -p vendor
      pushd vendor
      tar xfz "/data/cache/nodist/jdk-8u112-linux-x64.tar.gz"
      ln -nfs "jdk1.8.0_112" "jdk"
      popd
      ;;
  esac
}

bootstrap
