#!/usr/bin/env bash

function _java_profile {
  local shome="${_java_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  if [[ -d "$shome/vendor/jdk/bin" ]]; then
    PATH="$shome/vendor/jdk/bin:$PATH"
    export JAVA_HOME="$shome/vendor/jdk"
  fi
}

_java_profile
