#!/usr/bin/env bash

function _java_profile {
  local shome="${_java_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  JAVA_VERSION='1.8.0_131'

  if [[ -d "$shome/vendor/jdk${JAVA_VERSION}/bin" ]]; then
    PATH="$shome/vendor/jdk${JAVA_VERSION}/bin:$PATH"
    export JAVA_HOME="$shome/vendor/jdk${JAVA_VERSION}"
  fi
}

_java_profile
