#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$(java -version 2>&1 | head -1 | cut -d'"' -f2)" == "1.8.0_92" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
